### ISSUE TITLE
Make updates to EPS component sticker sheet

### ISSUE THREAD

**Issue by juliasolorzano** [uswds/uswds-for-designers#41]
This idea proposal was submitting to us via email by Isabelle Giuong. Here is what she wrote:

> Regarding the style guide "uswds-assets-eps/Components/Components_sticker_sheet":
> 1. Add a cover/title (and end/closing) page. 
> 2. Definitely have a table of contents (bonus usability points for making it navigable on Adobe PDF Reader, Word, or any other form). This will help people easily find what they need in this reference guide.
> 3. Break the content up more. It's pretty, but not very readable; some text are too small and having too many things too closely together makes the eyes wander without focus. 
> 4. Each page should be the same size.

**Comment by bradnunnally** [comment]
Some thoughts as I review the feedback that was submitted

- The EPS is meant to be a resource for quickly creating comps or wireframes, but it sounds like the original poster was flagging these issues as if it's a reference document. 
- Should we create a reference document that people can read and review that goes over the components, so a design spec rather than a sticker sheet?

Thoughts? @juliaelman @yowill @shawnbot 

If the decision is to create a reference design spec, I'd recommend closing this issue and creating a new one for creating the spec.

**Comment by bradnunnally** [comment]
Closing this and refocusing the ask with issue #44
